# Generated by Django 4.0 on 2022-01-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobiles_fiturs_model',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('idd', models.IntegerField(primary_key=True, serialize=False)),
                ('ram', models.CharField(max_length=20)),
                ('rom', models.CharField(max_length=20)),
                ('storage', models.CharField(max_length=20)),
                ('camera', models.CharField(max_length=20)),
                ('android_version', models.CharField(max_length=20)),
                ('warranty', models.CharField(max_length=20)),
            ],
        ),
    ]
